"""Letta tool: generate_image — Gemini 2.5 Flash Image (Nano Banana) + MinIO storage.

Uses only `requests` + stdlib (hashlib/hmac) — no `minio`/`boto3` dependency,
since the Letta execution sandbox ships a minimal Python environment.

Env vars (set as tool_exec_environment_variables on each agent that uses this):
    GEMINI_API_KEY    — Google AI Studio key with gemini-2.5-flash-image access
    MINIO_ENDPOINT    — internal host:port (e.g.
                        minio-tenant-hl.minio.svc.cluster.local:9000)
    MINIO_ACCESS_KEY  — per-app MinIO credentials
    MINIO_SECRET_KEY
    MINIO_BUCKET      — per-app bucket (e.g. "guruji")
    MINIO_PUBLIC_HOST — public hostname for presigned URLs (default: s3.baisoln.com)
    MINIO_REGION      — SigV4 region (default: us-east-1)
    LETTA_BASE_URL    — Letta server URL for self-call (archival memory insert)
    LETTA_API_KEY
    LETTA_AGENT_ID    — current agent ID, used to scope archival entry
"""


def generate_image(prompt: str, title: str = "") -> str:
    """Generate an educational image using Gemini Nano Banana and store it in MinIO.

    Use this tool whenever a visual would genuinely help the student understand
    a concept: diagrams, illustrations, worked examples, graphs, physical setups,
    geometric constructions, field lines, waveforms, molecular structures, etc.

    The image is generated by gemini-2.5-flash-image, stored permanently in
    the app's MinIO bucket, and returned as a 24-hour presigned URL. A metadata
    record is auto-inserted into archival memory so you can recall the image
    in future sessions via archival_memory_search.

    Keep prompts specific and style-consistent: say "clean educational line art,
    labels in English, white background" to get textbook-style diagrams.

    Args:
        prompt: Detailed description of the image to generate. Include style
            (e.g. "clean educational line art"), composition, labels, and any
            constraints. Example: "A clean educational diagram of a carbon
            atom: nucleus with 6 protons and 6 neutrons labeled, two electron
            shells with 2 and 4 electrons respectively, simple line art style,
            labels in English, white background."
        title: Short human-readable title (under ~60 chars) shown under the
            image in the chat panel. Defaults to a truncated prompt if empty.

    Returns:
        JSON string with artifact metadata. The frontend automatically renders
        the image from the presigned URL. After calling this tool, briefly
        mention that you've prepared the visual so the student knows to look
        at the chat panel. On error, returns {"error": "..."} — do NOT claim
        the image is visible if the tool returned an error.
    """
    import base64
    import datetime as _dt
    import hashlib
    import hmac
    import json as _json
    import os
    import urllib.parse
    import uuid

    import requests

    # ── Load config from env ────────────────────────────────────────
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    minio_endpoint = os.environ.get("MINIO_ENDPOINT", "").strip()
    minio_access = os.environ.get("MINIO_ACCESS_KEY", "").strip()
    minio_secret = os.environ.get("MINIO_SECRET_KEY", "").strip()
    minio_bucket = os.environ.get("MINIO_BUCKET", "").strip()
    minio_public_host = os.environ.get("MINIO_PUBLIC_HOST", "s3.baisoln.com").strip()
    minio_region = os.environ.get("MINIO_REGION", "us-east-1").strip()
    letta_base = os.environ.get("LETTA_BASE_URL", "").strip().rstrip("/")
    letta_key = os.environ.get("LETTA_API_KEY", "").strip()
    letta_agent_id = os.environ.get("LETTA_AGENT_ID", "").strip()

    if not api_key:
        return _json.dumps({"error": "GEMINI_API_KEY not configured for this tool"})
    if not all([minio_endpoint, minio_access, minio_secret, minio_bucket]):
        return _json.dumps(
            {"error": "MinIO config missing — need MINIO_ENDPOINT, MINIO_ACCESS_KEY, MINIO_SECRET_KEY, MINIO_BUCKET"}
        )

    if not title:
        title = (prompt[:60] + "...") if len(prompt) > 60 else prompt
    title = title.strip()

    # ── SigV4 helpers (S3-compatible) ───────────────────────────────
    def _sha256_hex(data):
        if isinstance(data, str):
            data = data.encode("utf-8")
        return hashlib.sha256(data).hexdigest()

    def _hmac_sha256(key, msg):
        if isinstance(msg, str):
            msg = msg.encode("utf-8")
        return hmac.new(key, msg, hashlib.sha256).digest()

    def _signing_key(secret, datestamp, region, service):
        k_date = _hmac_sha256(("AWS4" + secret).encode("utf-8"), datestamp)
        k_region = _hmac_sha256(k_date, region)
        k_service = _hmac_sha256(k_region, service)
        return _hmac_sha256(k_service, "aws4_request")

    def _s3_put(scheme, host, bucket, key, body_bytes, content_type, access_key, secret_key, region):
        """Perform an authenticated S3 PUT using SigV4 path-style."""
        service = "s3"
        now = _dt.datetime.utcnow()
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        datestamp = now.strftime("%Y%m%d")

        canonical_uri = "/" + bucket + "/" + urllib.parse.quote(key, safe="/")
        canonical_query = ""
        payload_hash = _sha256_hex(body_bytes)

        canonical_headers = (
            f"content-length:{len(body_bytes)}\n"
            f"content-type:{content_type}\n"
            f"host:{host}\n"
            f"x-amz-content-sha256:{payload_hash}\n"
            f"x-amz-date:{amz_date}\n"
        )
        signed_headers = "content-length;content-type;host;x-amz-content-sha256;x-amz-date"

        canonical_request = (
            f"PUT\n{canonical_uri}\n{canonical_query}\n"
            f"{canonical_headers}\n{signed_headers}\n{payload_hash}"
        )

        algorithm = "AWS4-HMAC-SHA256"
        credential_scope = f"{datestamp}/{region}/{service}/aws4_request"
        string_to_sign = (
            f"{algorithm}\n{amz_date}\n{credential_scope}\n"
            f"{_sha256_hex(canonical_request)}"
        )

        signing_key = _signing_key(secret_key, datestamp, region, service)
        signature = hmac.new(signing_key, string_to_sign.encode("utf-8"), hashlib.sha256).hexdigest()

        authorization = (
            f"{algorithm} Credential={access_key}/{credential_scope}, "
            f"SignedHeaders={signed_headers}, Signature={signature}"
        )

        headers = {
            "Host": host,
            "Content-Type": content_type,
            "Content-Length": str(len(body_bytes)),
            "x-amz-content-sha256": payload_hash,
            "x-amz-date": amz_date,
            "Authorization": authorization,
        }
        url = f"{scheme}://{host}{canonical_uri}"
        return requests.put(url, data=body_bytes, headers=headers, timeout=60)

    def _s3_presigned_get(host, bucket, key, access_key, secret_key, region, expires_seconds=86400):
        """Generate an S3 v4 presigned GET URL (path-style, HTTPS)."""
        service = "s3"
        now = _dt.datetime.utcnow()
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        datestamp = now.strftime("%Y%m%d")

        canonical_uri = "/" + bucket + "/" + urllib.parse.quote(key, safe="/")
        credential_scope = f"{datestamp}/{region}/{service}/aws4_request"

        # Query params that are part of the signature
        qp = {
            "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
            "X-Amz-Credential": f"{access_key}/{credential_scope}",
            "X-Amz-Date": amz_date,
            "X-Amz-Expires": str(expires_seconds),
            "X-Amz-SignedHeaders": "host",
        }
        canonical_query = "&".join(
            f"{urllib.parse.quote(k, safe='')}={urllib.parse.quote(v, safe='')}"
            for k, v in sorted(qp.items())
        )
        canonical_headers = f"host:{host}\n"
        signed_headers = "host"
        payload_hash = "UNSIGNED-PAYLOAD"

        canonical_request = (
            f"GET\n{canonical_uri}\n{canonical_query}\n"
            f"{canonical_headers}\n{signed_headers}\n{payload_hash}"
        )

        algorithm = "AWS4-HMAC-SHA256"
        string_to_sign = (
            f"{algorithm}\n{amz_date}\n{credential_scope}\n"
            f"{_sha256_hex(canonical_request)}"
        )
        signing_key = _signing_key(secret_key, datestamp, region, service)
        signature = hmac.new(signing_key, string_to_sign.encode("utf-8"), hashlib.sha256).hexdigest()

        return f"https://{host}{canonical_uri}?{canonical_query}&X-Amz-Signature={signature}"

    # ── Call Gemini Nano Banana ─────────────────────────────────────
    model = "gemini-2.5-flash-image"
    gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    body = {"contents": [{"parts": [{"text": prompt}]}]}
    try:
        resp = requests.post(gemini_url, json=body, timeout=120)
        resp.raise_for_status()
        data = resp.json()
    except requests.HTTPError as e:
        body_preview = ""
        try:
            body_preview = resp.text[:400]
        except Exception:
            pass
        return _json.dumps({"error": f"Gemini API error: {e}", "body": body_preview})
    except requests.RequestException as e:
        return _json.dumps({"error": f"Gemini request failed: {e}"})

    cands = data.get("candidates") or []
    if not cands:
        return _json.dumps(
            {"error": "Gemini returned no candidates (possibly safety-filtered)", "raw": str(data)[:300]}
        )

    png_bytes = None
    mime_type = "image/png"
    for part in cands[0].get("content", {}).get("parts", []):
        inline = part.get("inlineData") or part.get("inline_data")
        if inline and inline.get("data"):
            png_bytes = base64.b64decode(inline["data"])
            mime_type = inline.get("mimeType") or inline.get("mime_type") or "image/png"
            break

    if not png_bytes:
        return _json.dumps(
            {"error": "Gemini returned no image (possibly safety-filtered)", "raw": str(data)[:300]}
        )

    # ── Upload to MinIO via internal endpoint using SigV4 ──────────
    internal_host = minio_endpoint.replace("http://", "").replace("https://", "").rstrip("/")
    now = _dt.datetime.utcnow()
    obj_id = uuid.uuid4().hex[:12]
    agent_dir = letta_agent_id or "shared"
    object_key = f"letta-artifacts/images/{agent_dir}/{now.strftime('%Y%m%d')}/{obj_id}.png"

    try:
        put_resp = _s3_put(
            scheme="http",
            host=internal_host,
            bucket=minio_bucket,
            key=object_key,
            body_bytes=png_bytes,
            content_type=mime_type,
            access_key=minio_access,
            secret_key=minio_secret,
            region=minio_region,
        )
    except Exception as e:
        return _json.dumps({"error": f"MinIO PUT request failed: {e}"})

    if put_resp.status_code not in (200, 201):
        return _json.dumps(
            {
                "error": f"MinIO PUT failed: HTTP {put_resp.status_code}",
                "body": put_resp.text[:400],
                "key": object_key,
            }
        )

    internal_s3_url = f"s3://{minio_bucket}/{object_key}"

    # ── Generate 24h presigned URL against public host ─────────────
    try:
        presigned_url = _s3_presigned_get(
            host=minio_public_host,
            bucket=minio_bucket,
            key=object_key,
            access_key=minio_access,
            secret_key=minio_secret,
            region=minio_region,
            expires_seconds=86400,
        )
    except Exception as e:
        return _json.dumps({"error": f"Presigned URL generation failed: {e}"})

    # ── Insert archival memory entry (non-fatal on failure) ────────
    archival_inserted = False
    archival_error = None
    if letta_base and letta_key and letta_agent_id:
        try:
            archival_text = (
                f"[IMAGE ARTIFACT] {title}\n"
                f"Prompt: {prompt}\n"
                f"S3 URL: {internal_s3_url}\n"
                f"Bucket: {minio_bucket}, Key: {object_key}\n"
                f"Created: {now.isoformat()}Z\n"
                f"Content-Type: {mime_type}, Size: {len(png_bytes)} bytes\n"
                f"To recall: search archival for '{title}' or object id '{obj_id}'. "
                f"A fresh 24h presigned URL will be regenerated by the agent pod "
                f"when this artifact is referenced in a future session."
            )
            ar_resp = requests.post(
                f"{letta_base}/v1/agents/{letta_agent_id}/archival-memory",
                headers={
                    "Authorization": f"Bearer {letta_key}",
                    "Content-Type": "application/json",
                },
                json={"text": archival_text},
                timeout=15,
            )
            archival_inserted = ar_resp.status_code < 400
            if not archival_inserted:
                archival_error = f"HTTP {ar_resp.status_code}: {ar_resp.text[:200]}"
        except Exception as e:
            archival_error = str(e)[:200]

    # ── Return artifact payload ─────────────────────────────────────
    created_iso = now.isoformat() + "Z"
    expires_iso = (now + _dt.timedelta(hours=24)).isoformat() + "Z"

    result = {
        "type": "image_artifact",
        "title": title,
        "prompt": prompt,
        "internal_s3_url": internal_s3_url,
        "bucket": minio_bucket,
        "object_key": object_key,
        "content_type": mime_type,
        "size_bytes": len(png_bytes),
        "created_at": created_iso,
        "expires_at": expires_iso,
        "agent_id": letta_agent_id,
        "presigned_url": presigned_url,
        "archival_inserted": archival_inserted,
        "archival_error": archival_error,
        # Pre-formatted for _parse_letta_response in the agent pod:
        "summary": f"Generated image: {title}",
        "artifacts": [
            {
                "title": title,
                "path": presigned_url,
                "url": presigned_url,
                "content_type": mime_type,
                "summary": f"Image: {title}",
                "subtype": "image",
                "internal_s3_url": internal_s3_url,
            }
        ],
    }
    return _json.dumps(result)
