apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bionic-platform-secrets
  namespace: bionic-platform
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bionic-platform-secrets
  dataFrom:
    - extract:
        key: t6-apps/bionic-platform/config
