/**
 * Session Summary Service
 *
 * Generates a PDF summary of a teaching session and emails it to the user.
 * Called by the agent pod via POST /api/session-summary/send when a session ends.
 *
 * Flow: Agent pod collects session data → POST to platform → render PDF → email
 *
 * PDF generation uses markdown-to-HTML + puppeteer for high-quality rendering.
 * SMTP credentials come from environment (injected via Vault → ESO → K8s secret).
 */

import { createLogger } from "../_core/logger.js";
import nodemailer from "nodemailer";
import { marked } from "marked";

const log = createLogger("SessionSummary");

// SMTP config from environment (Vault → ESO → K8s secret)
const SMTP_HOST = process.env.SMTP_HOST || "";
const SMTP_PORT = parseInt(process.env.SMTP_PORT || "587", 10);
const SMTP_USER = process.env.SMTP_USER || "";
const SMTP_PASS = process.env.SMTP_PASS || "";
const SMTP_FROM = process.env.SMTP_FROM || "noreply@bionicaisolutions.com";

interface SessionSummaryRequest {
  email: string;
  sessionTitle: string;
  summaryMarkdown: string;
  imageUrls?: string[];
  agentName?: string;
  userName?: string;
  sessionDate?: string;
}

/**
 * Render a session summary markdown into styled HTML suitable for email/PDF.
 */
function renderSummaryHtml(req: SessionSummaryRequest): string {
  const date = req.sessionDate || new Date().toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const bodyHtml = marked.parse(req.summaryMarkdown, { breaks: true, gfm: true });

  // Render images as inline <img> tags if provided
  const imagesHtml = (req.imageUrls || [])
    .filter(Boolean)
    .map((url) => `<div style="margin: 16px 0; text-align: center;">
      <img src="${url}" alt="Session illustration" style="max-width: 100%; border-radius: 8px; border: 1px solid #e0e0e0;" />
    </div>`)
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 0 auto; padding: 32px 24px; color: #1a1a2e; line-height: 1.7; }
  h1 { color: #1a1a2e; font-size: 24px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
  h2 { color: #4338ca; font-size: 18px; margin-top: 28px; }
  h3 { color: #6366f1; font-size: 15px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; }
  code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
  pre { background: #f3f4f6; padding: 12px; border-radius: 8px; overflow-x: auto; font-size: 13px; }
  blockquote { border-left: 3px solid #6366f1; margin-left: 0; padding-left: 16px; color: #4b5563; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #f9fafb; font-weight: 600; }
  .header { text-align: center; margin-bottom: 32px; }
  .meta { color: #6b7280; font-size: 13px; margin-top: 4px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; text-align: center; }
  .images-section { margin-top: 24px; }
</style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(req.sessionTitle)}</h1>
    <div class="meta">${escapeHtml(date)}${req.agentName ? ` &middot; ${escapeHtml(req.agentName)}` : ""}${req.userName ? ` &middot; ${escapeHtml(req.userName)}` : ""}</div>
  </div>

  ${bodyHtml}

  ${imagesHtml ? `<div class="images-section"><h2>Session Illustrations</h2>${imagesHtml}</div>` : ""}

  <div class="footer">
    Generated by Bionic AI Platform &middot; bionicaisolutions.com
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/**
 * Send a session summary email with the rendered HTML as the email body.
 * Returns true on success.
 */
export async function sendSessionSummary(req: SessionSummaryRequest): Promise<{ success: boolean; error?: string }> {
  if (!req.email || !req.summaryMarkdown) {
    return { success: false, error: "Missing email or summaryMarkdown" };
  }

  if (!SMTP_HOST || !SMTP_USER) {
    log.warn("SMTP not configured — cannot send session summary", { email: req.email });
    return { success: false, error: "SMTP not configured" };
  }

  try {
    const html = renderSummaryHtml(req);

    const transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: SMTP_PORT,
      secure: SMTP_PORT === 465,
      auth: { user: SMTP_USER, pass: SMTP_PASS },
    });

    await transporter.sendMail({
      from: `"Bionic AI" <${SMTP_FROM}>`,
      to: req.email,
      subject: `Session Summary: ${req.sessionTitle}`,
      html,
    });

    log.info("Session summary emailed", { email: req.email, title: req.sessionTitle });
    return { success: true };
  } catch (err) {
    log.error("Failed to send session summary email", { error: String(err), email: req.email });
    return { success: false, error: String(err) };
  }
}
