"""Letta tool: generate_persona_image — photorealistic persona avatar via Gemini + MinIO.

Generates a photorealistic portrait image from structured persona parameters
(profession, appearance, environment, etc.) using a detailed template prompt.
Stores the image in MinIO and updates the agent's avatar in the platform DB
so it can be applied to BitHuman on next deployment.

Uses only `requests` + stdlib (hashlib/hmac) — no `minio`/`boto3` dependency,
since the Letta execution sandbox ships a minimal Python environment.

Env vars (set as tool_exec_environment_variables on each agent that uses this):
    GEMINI_API_KEY      — Google AI Studio key with gemini-2.5-flash-image access
    MINIO_ENDPOINT      — internal host:port
    MINIO_ACCESS_KEY    — per-app MinIO credentials
    MINIO_SECRET_KEY
    MINIO_BUCKET        — per-app bucket
    MINIO_PUBLIC_HOST   — public hostname for presigned URLs (default: s3.baisoln.com)
    MINIO_REGION        — SigV4 region (default: us-east-1)
    LETTA_BASE_URL      — Letta server URL for archival memory insert
    LETTA_API_KEY
    LETTA_AGENT_ID      — current agent ID
    PLATFORM_API_URL    — internal platform server URL for avatar update
    AGENT_INTERNAL_TOKEN — shared secret for internal API auth
    AGENT_CONFIG_ID     — platform DB ID for this agent config
"""


def generate_persona_image(
    profession: str,
    age_range: str = "30s",
    appearance: str = "",
    table_type: str = "",
    gear_items: str = "",
    primary_item: str = "",
    item_position: str = "right",
    environment_description: str = "",
    environment_details: str = "",
    lighting_type: str = "",
    mood: str = "",
    color_palette: str = "",
    aspect_ratio: str = "1:1",
) -> str:
    """Generate a photorealistic persona avatar image and set it as this agent's avatar.

    Creates a detailed, posed portrait of a professional in their work environment
    using structured parameters. The image is generated by Gemini, stored in MinIO,
    and automatically set as this agent's BitHuman avatar. The new avatar takes
    effect on the next agent deployment/session restart.

    Use this tool when:
    - Setting up a new agent persona (e.g. "make this agent look like a doctor")
    - The user asks to change the agent's appearance or avatar
    - Creating a visual identity for the agent based on a profession

    Only the `profession` parameter is required. All other parameters have sensible
    defaults derived from the profession if left empty.

    Args:
        profession: The profession for the persona (e.g. "astronaut", "doctor",
            "surgeon", "firefighter", "chef", "teacher", "software engineer").
        age_range: Age range description (e.g. "30s", "late 40s", "early 50s").
        appearance: Brief appearance details — gender expression, ethnicity,
            hairstyle, clothing style. Example: "female, East Asian, shoulder-length
            black hair, wearing light blue scrubs".
        table_type: Type of table/surface in the portrait (e.g. "brushed metal
            table", "oak desk", "stainless-steel prep table"). Defaults based
            on profession.
        gear_items: Professional gear laid out on the table. Example: "thick white
            gloves, wrist-mounted checklist device, equipment pouches". Defaults
            based on profession.
        primary_item: The main item they are about to put on (e.g. "space helmet
            with gold visor", "stethoscope", "surgical gloves"). Defaults based
            on profession.
        item_position: Position of primary item — "left" or "right".
        environment_description: Short environment description (e.g. "pre-launch
            prep room in a space center"). Defaults based on profession.
        environment_details: 3-6 specific background props (e.g. "wall-mounted
            countdown clock, mission patch mural, coiled cables"). Defaults
            based on profession.
        lighting_type: Lighting description (e.g. "soft cool overhead lighting",
            "warm tungsten", "cinematic three-point lighting"). Defaults based
            on profession.
        mood: Atmosphere mood (e.g. "focused and determined", "calm and
            reassuring", "serious and high-stakes"). Defaults based on profession.
        color_palette: Color grading description (e.g. "cool blues and neutrals",
            "warm earth tones"). Defaults based on profession.
        aspect_ratio: Image aspect ratio (e.g. "1:1", "4:5 portrait",
            "16:9 landscape"). Default "1:1" for avatar use.

    Returns:
        JSON string with the presigned URL of the generated avatar, MinIO path,
        and status of the avatar update. The avatar will be applied on next
        deployment. On error, returns {"error": "..."}.
    """
    import base64
    import datetime as _dt
    import hashlib
    import hmac
    import json as _json
    import os
    import urllib.parse
    import uuid

    import requests

    # ── Load config from env ────────────────────────────────────────
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    minio_endpoint = os.environ.get("MINIO_ENDPOINT", "").strip()
    minio_access = os.environ.get("MINIO_ACCESS_KEY", "").strip()
    minio_secret = os.environ.get("MINIO_SECRET_KEY", "").strip()
    minio_bucket = os.environ.get("MINIO_BUCKET", "").strip()
    minio_public_host = os.environ.get("MINIO_PUBLIC_HOST", "s3.baisoln.com").strip()
    minio_region = os.environ.get("MINIO_REGION", "us-east-1").strip()
    letta_base = os.environ.get("LETTA_BASE_URL", "").strip().rstrip("/")
    letta_key = os.environ.get("LETTA_API_KEY", "").strip()
    letta_agent_id = os.environ.get("LETTA_AGENT_ID", "").strip()
    platform_api_url = os.environ.get("PLATFORM_API_URL", "").strip().rstrip("/")
    agent_internal_token = os.environ.get("AGENT_INTERNAL_TOKEN", "").strip()
    agent_config_id = os.environ.get("AGENT_CONFIG_ID", "").strip()

    if not api_key:
        return _json.dumps({"error": "GEMINI_API_KEY not configured for this tool"})
    if not all([minio_endpoint, minio_access, minio_secret, minio_bucket]):
        return _json.dumps(
            {"error": "MinIO config missing — need MINIO_ENDPOINT, MINIO_ACCESS_KEY, MINIO_SECRET_KEY, MINIO_BUCKET"}
        )

    # ── Profession-based defaults ──────────────────────────────────
    # When optional parameters are empty, derive sensible defaults from
    # the profession to produce a coherent, detailed prompt.
    _PROFESSION_DEFAULTS = {
        "astronaut": {
            "table_type": "brushed metal table",
            "gear_items": "thick white gloves with gray gripping pads, a slim wrist-mounted checklist device, and a few small labeled equipment pouches",
            "primary_item": "a large white space helmet with a gold-tinted visor",
            "environment_description": "a pre-launch preparation room in a space center",
            "environment_details": "white and light gray walls, storage lockers, a large mission patch mural, a window showing a blurred view of the launch pad, coiled cables on a wall rack, a wall-mounted digital countdown clock, laminated safety procedure sheets clipped to a board",
            "lighting_type": "soft, cool overhead lighting with a subtle side key light",
            "mood": "focused and determined",
            "color_palette": "cool blues and neutral grays",
        },
        "doctor": {
            "table_type": "clean white consultation table",
            "gear_items": "a digital tablet showing a blurred medical chart, a clipboard with paperwork, a pen, a small blood pressure cuff, and a prescription pad",
            "primary_item": "a stethoscope",
            "environment_description": "a modern medical exam room",
            "environment_details": "soft white and light blue walls, a wall-mounted anatomical poster, closed cabinets with medical supplies, a partially visible exam bed, a wall-mounted hand-sanitizer dispenser, a digital wall clock, a small potted plant",
            "lighting_type": "soft, diffused clinic lighting with a gentle key light from one side",
            "mood": "calm and reassuring",
            "color_palette": "whites, light blues, and subtle greys",
        },
        "surgeon": {
            "table_type": "stainless-steel prep table",
            "gear_items": "a lined-up set of stainless-steel instruments (scalpel, forceps, clamps, scissors), a folded sterile drape, a small tray with gauze pads",
            "primary_item": "a pair of sterile surgical gloves still in their packaging",
            "environment_description": "a modern operating room environment",
            "environment_details": "blurred surgical lights overhead, equipment monitors with soft blue and green glow, an IV stand, wall-mounted oxygen and suction outlets, coiled cables, a cart with covered instruments",
            "lighting_type": "cool, focused operating-room lighting with a bright key light from above",
            "mood": "serious and high-stakes",
            "color_palette": "cool blue and teal with hints of white",
        },
        "chef": {
            "table_type": "stainless-steel kitchen prep counter",
            "gear_items": "a set of professional knives in a leather roll, a worn wooden cutting board, fresh herbs and spices in small bowls, a folded kitchen towel",
            "primary_item": "a tall white chef's toque (chef's hat)",
            "environment_description": "a busy restaurant kitchen line",
            "environment_details": "hanging copper pots and pans, a large commercial range with blue gas flames, stacked white plates ready for plating, a chalkboard menu on the wall, stainless-steel shelving with labeled containers, a ticket rail with orders",
            "lighting_type": "warm tungsten overhead lighting",
            "mood": "passionate and energetic",
            "color_palette": "warm earth tones with stainless steel accents",
        },
        "teacher": {
            "table_type": "wooden teacher's desk",
            "gear_items": "a stack of graded papers with a red pen, a laptop open to a lesson plan, colorful sticky notes, a coffee mug, a small globe",
            "primary_item": "reading glasses",
            "environment_description": "a bright, welcoming classroom",
            "environment_details": "a whiteboard with lesson notes, colorful educational posters on the walls, shelves with books and learning materials, student desks in the background, a window letting in natural light, a world map",
            "lighting_type": "bright, natural daylight from large windows",
            "mood": "warm and encouraging",
            "color_palette": "warm yellows, soft greens, and natural wood tones",
        },
        "firefighter": {
            "table_type": "heavy-duty metal equipment bench",
            "gear_items": "a pair of heat-resistant gloves, an oxygen mask with regulator, a hand-held radio, reflective turnout coat folded neatly",
            "primary_item": "a bright red firefighter helmet with face shield",
            "environment_description": "a fire station equipment bay",
            "environment_details": "a red fire engine visible in the background, rows of turnout gear on hooks, coiled fire hoses, a pole in the corner, a large station number on the wall, a wall-mounted AED unit",
            "lighting_type": "warm overhead fluorescent mixed with daylight from the bay door",
            "mood": "brave and ready",
            "color_palette": "warm reds, yellows, and industrial grays",
        },
        "software_engineer": {
            "table_type": "modern standing desk with a dark wood top",
            "gear_items": "a mechanical keyboard, dual monitors showing code, noise-canceling headphones, a notebook with system diagrams, a coffee cup",
            "primary_item": "noise-canceling headphones",
            "environment_description": "a modern tech office or home studio",
            "environment_details": "dual ultrawide monitors with code on screen, LED strip lighting behind the desk, a whiteboard with architecture diagrams, potted plants, scattered sticky notes, a bookshelf with technical books",
            "lighting_type": "soft ambient LED lighting with cool monitor glow",
            "mood": "focused and creative",
            "color_palette": "cool blues, dark grays, and accent greens",
        },
    }

    # Look up defaults — try exact match, then fuzzy
    prof_lower = profession.lower().strip().replace(" ", "_")
    defaults = _PROFESSION_DEFAULTS.get(prof_lower, {})
    if not defaults:
        # Try partial match
        for key, val in _PROFESSION_DEFAULTS.items():
            if key in prof_lower or prof_lower in key:
                defaults = val
                break

    # Apply defaults for empty parameters
    _table_type = table_type or defaults.get("table_type", "wooden desk")
    _gear_items = gear_items or defaults.get("gear_items", f"professional tools and equipment typical of a {profession}")
    _primary_item = primary_item or defaults.get("primary_item", f"the most recognizable item associated with a {profession}")
    _env_desc = environment_description or defaults.get("environment_description", f"a typical {profession} work environment")
    _env_details = environment_details or defaults.get("environment_details", f"authentic props and background elements tied to the {profession} profession")
    _lighting = lighting_type or defaults.get("lighting_type", "soft natural window light")
    _mood = mood or defaults.get("mood", "calm and professional")
    _color_palette = color_palette or defaults.get("color_palette", "warm earth tones")
    _appearance = appearance or "professional appearance, natural look"

    # ── Build the prompt from template ─────────────────────────────
    prompt = (
        f"Create a photorealistic image of a {profession} in their late {age_range} "
        f"with {_appearance}, sitting at a {_table_type} and facing the camera for a "
        f"posed portrait. The person is in the process of getting ready for work, with "
        f"their primary professional gear or uniform pieces laid out neatly on the "
        f"table: {_gear_items}. The main item they are about to put on, {_primary_item}, "
        f"is on the table to their {item_position}, clearly visible in the frame.\n\n"
        f"The background should clearly reflect a {profession}-appropriate environment, "
        f"such as {_env_desc}. Add environment details that feel authentic to this "
        f"profession: {_env_details}.\n\n"
        f"Composition: medium shot from the waist up, subject seated at the table, "
        f"centered in frame, making calm eye contact with the camera, hands resting "
        f"lightly on or near the gear on the table. Use a shallow depth of field so "
        f"the {profession} and the gear on the table are in sharp focus while the "
        f"background is softly blurred.\n\n"
        f"Lighting and mood: {_lighting} that creates gentle highlights on the "
        f"person's face and on the key gear items, with a {_mood} atmosphere.\n\n"
        f"Style: highly detailed, natural skin textures, realistic materials and "
        f"reflections on the gear, subtle color grading with {_color_palette}. "
        f"Aspect ratio {aspect_ratio}."
    )

    title = f"{profession.title()} Persona Avatar"

    # ── SigV4 helpers (S3-compatible) ───────────────────────────────
    def _sha256_hex(data):
        if isinstance(data, str):
            data = data.encode("utf-8")
        return hashlib.sha256(data).hexdigest()

    def _hmac_sha256(key, msg):
        if isinstance(msg, str):
            msg = msg.encode("utf-8")
        return hmac.new(key, msg, hashlib.sha256).digest()

    def _signing_key(secret, datestamp, region, service):
        k_date = _hmac_sha256(("AWS4" + secret).encode("utf-8"), datestamp)
        k_region = _hmac_sha256(k_date, region)
        k_service = _hmac_sha256(k_region, service)
        return _hmac_sha256(k_service, "aws4_request")

    def _s3_put(scheme, host, bucket, key, body_bytes, content_type, access_key, secret_key, region):
        """Perform an authenticated S3 PUT using SigV4 path-style."""
        service = "s3"
        now = _dt.datetime.utcnow()
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        datestamp = now.strftime("%Y%m%d")

        canonical_uri = "/" + bucket + "/" + urllib.parse.quote(key, safe="/")
        canonical_query = ""
        payload_hash = _sha256_hex(body_bytes)

        canonical_headers = (
            f"content-length:{len(body_bytes)}\n"
            f"content-type:{content_type}\n"
            f"host:{host}\n"
            f"x-amz-content-sha256:{payload_hash}\n"
            f"x-amz-date:{amz_date}\n"
        )
        signed_headers = "content-length;content-type;host;x-amz-content-sha256;x-amz-date"

        canonical_request = (
            f"PUT\n{canonical_uri}\n{canonical_query}\n"
            f"{canonical_headers}\n{signed_headers}\n{payload_hash}"
        )

        algorithm = "AWS4-HMAC-SHA256"
        credential_scope = f"{datestamp}/{region}/{service}/aws4_request"
        string_to_sign = (
            f"{algorithm}\n{amz_date}\n{credential_scope}\n"
            f"{_sha256_hex(canonical_request)}"
        )

        signing_key = _signing_key(secret_key, datestamp, region, service)
        signature = hmac.new(signing_key, string_to_sign.encode("utf-8"), hashlib.sha256).hexdigest()

        authorization = (
            f"{algorithm} Credential={access_key}/{credential_scope}, "
            f"SignedHeaders={signed_headers}, Signature={signature}"
        )

        headers = {
            "Host": host,
            "Content-Type": content_type,
            "Content-Length": str(len(body_bytes)),
            "x-amz-content-sha256": payload_hash,
            "x-amz-date": amz_date,
            "Authorization": authorization,
        }
        url = f"{scheme}://{host}{canonical_uri}"
        return requests.put(url, data=body_bytes, headers=headers, timeout=60)

    def _s3_presigned_get(host, bucket, key, access_key, secret_key, region, expires_seconds=86400):
        """Generate an S3 v4 presigned GET URL (path-style, HTTPS)."""
        service = "s3"
        now = _dt.datetime.utcnow()
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        datestamp = now.strftime("%Y%m%d")

        canonical_uri = "/" + bucket + "/" + urllib.parse.quote(key, safe="/")
        credential_scope = f"{datestamp}/{region}/{service}/aws4_request"

        qp = {
            "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
            "X-Amz-Credential": f"{access_key}/{credential_scope}",
            "X-Amz-Date": amz_date,
            "X-Amz-Expires": str(expires_seconds),
            "X-Amz-SignedHeaders": "host",
        }
        canonical_query = "&".join(
            f"{urllib.parse.quote(k, safe='')}={urllib.parse.quote(v, safe='')}"
            for k, v in sorted(qp.items())
        )
        canonical_headers = f"host:{host}\n"
        signed_headers = "host"
        payload_hash = "UNSIGNED-PAYLOAD"

        canonical_request = (
            f"GET\n{canonical_uri}\n{canonical_query}\n"
            f"{canonical_headers}\n{signed_headers}\n{payload_hash}"
        )

        algorithm = "AWS4-HMAC-SHA256"
        string_to_sign = (
            f"{algorithm}\n{amz_date}\n{credential_scope}\n"
            f"{_sha256_hex(canonical_request)}"
        )
        signing_key = _signing_key(secret_key, datestamp, region, service)
        signature = hmac.new(signing_key, string_to_sign.encode("utf-8"), hashlib.sha256).hexdigest()

        return f"https://{host}{canonical_uri}?{canonical_query}&X-Amz-Signature={signature}"

    # ── Call Gemini 2.5 Flash Image ────────────────────────────────
    model = "gemini-2.5-flash-image"
    gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    body = {"contents": [{"parts": [{"text": prompt}]}]}
    try:
        resp = requests.post(gemini_url, json=body, timeout=120)
        resp.raise_for_status()
        data = resp.json()
    except requests.HTTPError as e:
        body_preview = ""
        try:
            body_preview = resp.text[:400]
        except Exception:
            pass
        return _json.dumps({"error": f"Gemini API error: {e}", "body": body_preview})
    except requests.RequestException as e:
        return _json.dumps({"error": f"Gemini request failed: {e}"})

    cands = data.get("candidates") or []
    if not cands:
        return _json.dumps(
            {"error": "Gemini returned no candidates (possibly safety-filtered)", "raw": str(data)[:300]}
        )

    png_bytes = None
    mime_type = "image/png"
    for part in cands[0].get("content", {}).get("parts", []):
        inline = part.get("inlineData") or part.get("inline_data")
        if inline and inline.get("data"):
            png_bytes = base64.b64decode(inline["data"])
            mime_type = inline.get("mimeType") or inline.get("mime_type") or "image/png"
            break

    if not png_bytes:
        return _json.dumps(
            {"error": "Gemini returned no image (possibly safety-filtered)", "raw": str(data)[:300]}
        )

    # ── Upload to MinIO at the avatar path convention ──────────────
    internal_host = minio_endpoint.replace("http://", "").replace("https://", "").rstrip("/")
    now = _dt.datetime.utcnow()
    obj_id = uuid.uuid4().hex[:12]
    # Use the avatar path convention so it matches uploadAvatarImage
    config_id = agent_config_id or "shared"
    object_key = f"avatars/{config_id}/persona-{obj_id}.png"

    try:
        put_resp = _s3_put(
            scheme="http",
            host=internal_host,
            bucket=minio_bucket,
            key=object_key,
            body_bytes=png_bytes,
            content_type=mime_type,
            access_key=minio_access,
            secret_key=minio_secret,
            region=minio_region,
        )
    except Exception as e:
        return _json.dumps({"error": f"MinIO PUT request failed: {e}"})

    if put_resp.status_code not in (200, 201):
        return _json.dumps(
            {
                "error": f"MinIO PUT failed: HTTP {put_resp.status_code}",
                "body": put_resp.text[:400],
                "key": object_key,
            }
        )

    minio_path = f"{minio_bucket}/{object_key}"
    internal_s3_url = f"s3://{minio_path}"

    # ── Generate presigned URL for preview ─────────────────────────
    try:
        presigned_url = _s3_presigned_get(
            host=minio_public_host,
            bucket=minio_bucket,
            key=object_key,
            access_key=minio_access,
            secret_key=minio_secret,
            region=minio_region,
            expires_seconds=86400,
        )
    except Exception as e:
        return _json.dumps({"error": f"Presigned URL generation failed: {e}"})

    # ── Update agent avatar in platform DB ─────────────────────────
    avatar_updated = False
    avatar_error = None
    if platform_api_url and agent_config_id:
        try:
            headers = {"Content-Type": "application/json"}
            if agent_internal_token:
                headers["X-Internal-Token"] = agent_internal_token
            update_resp = requests.post(
                f"{platform_api_url}/api/internal/agent/{agent_config_id}/avatar",
                headers=headers,
                json={"minioPath": minio_path},
                timeout=15,
            )
            avatar_updated = update_resp.status_code < 400
            if not avatar_updated:
                avatar_error = f"HTTP {update_resp.status_code}: {update_resp.text[:200]}"
        except Exception as e:
            avatar_error = str(e)[:200]
    else:
        avatar_error = "PLATFORM_API_URL or AGENT_CONFIG_ID not configured"

    # ── Insert archival memory entry (non-fatal) ───────────────────
    archival_inserted = False
    archival_error = None
    if letta_base and letta_key and letta_agent_id:
        try:
            archival_text = (
                f"[PERSONA AVATAR] {title}\n"
                f"Profession: {profession}\n"
                f"Prompt: {prompt[:500]}\n"
                f"S3 URL: {internal_s3_url}\n"
                f"Bucket: {minio_bucket}, Key: {object_key}\n"
                f"Created: {now.isoformat()}Z\n"
                f"Avatar updated in DB: {avatar_updated}\n"
                f"Note: avatar takes effect on next agent deployment/session restart."
            )
            ar_resp = requests.post(
                f"{letta_base}/v1/agents/{letta_agent_id}/archival-memory",
                headers={
                    "Authorization": f"Bearer {letta_key}",
                    "Content-Type": "application/json",
                },
                json={"text": archival_text},
                timeout=15,
            )
            archival_inserted = ar_resp.status_code < 400
            if not archival_inserted:
                archival_error = f"HTTP {ar_resp.status_code}: {ar_resp.text[:200]}"
        except Exception as e:
            archival_error = str(e)[:200]

    # ── Return result ──────────────────────────────────────────────
    created_iso = now.isoformat() + "Z"
    expires_iso = (now + _dt.timedelta(hours=24)).isoformat() + "Z"

    result = {
        "type": "persona_avatar",
        "title": title,
        "profession": profession,
        "prompt_used": prompt,
        "internal_s3_url": internal_s3_url,
        "minio_path": minio_path,
        "bucket": minio_bucket,
        "object_key": object_key,
        "content_type": mime_type,
        "size_bytes": len(png_bytes),
        "created_at": created_iso,
        "expires_at": expires_iso,
        "presigned_url": presigned_url,
        "avatar_updated": avatar_updated,
        "avatar_error": avatar_error,
        "archival_inserted": archival_inserted,
        "archival_error": archival_error,
        "message": (
            f"Generated {profession} persona avatar image. "
            + ("Avatar saved — it will be applied on the next agent deployment/session restart."
               if avatar_updated
               else f"Image generated but avatar update failed: {avatar_error}. "
                    "The image is still accessible via the presigned URL.")
        ),
        # Pre-formatted for _parse_letta_response in the agent pod:
        "summary": (
            f"Generated {profession} persona avatar. "
            + ("Will be applied on next deployment." if avatar_updated else f"Avatar update failed: {avatar_error}")
        ),
        "artifacts": [
            {
                "title": title,
                "path": presigned_url,
                "url": presigned_url,
                "content_type": mime_type,
                "summary": f"Persona avatar: {profession}",
                "subtype": "image",
                "internal_s3_url": internal_s3_url,
            }
        ],
    }
    return _json.dumps(result)
